# Generated by Django 6.0.3 on 2026-03-08 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='bio',
        ),
        migrations.DeleteModel(
            name='Bio',
        ),
    ]
