# Generated by Django 6.0.3 on 2026-03-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_remove_instructor_bio_delete_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='instructors/'),
        ),
    ]
